name: Super-Linter

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Gradle Build
        run:  ./gradlew build
      - name: Agent Notification1
        run: echo "test case with annotation includes double member"
      - name: Run Agent
        run: 'java -javaagent:$AGENT_PATH -jar $APP_PATH'
        env:
          AGENT_PATH: agent/build/libs/shadow-1.0-SNAPSHOT-all.jar
          APP_PATH: app/build/libs/app-1.0-SNAPSHOT.jar
      - name: Remove Double Mebmber
        run: sed -i "" 's/double/\/\/double/' app/src/main/java/org/example/Timed.java
      - name: Gradle Build
        run: ./gradlew build
      - name: Agent Notification2
        run: echo "test case with annotation excludes double member"
      - name: Run Agent Again
        run: 'java -javaagent:$AGENT_PATH -jar $APP_PATH'
        env:
          AGENT_PATH: agent/build/libs/shadow-1.0-SNAPSHOT-all.jar
          APP_PATH: app/build/libs/app-1.0-SNAPSHOT.jar