name: Super-Linter

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with agent Gradle
        run: agent/gradlew build
      - name: goto app folder
        run: cd app
      - name: Build with Gradle
        run: ./gradlew build
      - name: return repo root
        run: cd ..
      - name: Run Agent
        run: 'java -javaagent:$AGENT_PATH -jar $APP_PATH'
        env:
          AGENT_PATH: agent/build/libs/shadow-1.0-SNAPSHOT-all.jar
          APP_PATH: app/build/libs/app-1.0-SNAPSHOT.jar